### ISSUE TITLE
Index page and blog index page: blog abstract is spilled out of container

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma.com#14]
This must be a bug right?

![screen shot 2018-08-28 at 1 52 20 pm](https://user-images.githubusercontent.com/11865/44703284-9e8d2a00-aac9-11e8-9b27-e9dd3c4fe18b.png)

**Comment by strogonoff** [comment]
* https://github.com/riboseinc/jekyll-theme-open-project/issues/27
* https://github.com/asciidoctor/jekyll-asciidoc/issues/181

Specified the excerpt manually in this case in https://github.com/riboseinc/metanorma.com/commit/db6ab8603602d330bef1bd305dd0e5ac385e48a9.
