### ISSUE TITLE
"Pinning" of certain entries on top

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma.com#15]
We now have an number of software + specification entries on the front page, but obviously some are more important than others.

1. Can we use a grid view for better viewing?
2. Can we specify some "priority" value to sort with so that we can control the order?

![screen shot 2018-08-28 at 1 53 07 pm](https://user-images.githubusercontent.com/11865/44703509-7651fb00-aaca-11e8-81c6-71380953fee2.png)

**Comment by strogonoff** [comment]
I’m going to address the ordering, as this may be an immediate issue, and we’ll leave the grid layout idea open (might get Ricardo’s feedback on it)
