### ISSUE TITLE
Add Quickstart guide and Guidance to site

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma.com#19]
For authors, relevant documentation is available here:

* Quickstart guide: https://github.com/riboseinc/metanorma-iso/blob/master/docs/quickstart.adoc
* Guidance for Authoring: https://github.com/riboseinc/metanorma-iso/blob/master/docs/guidance.adoc

These guides should be shown prominently on metanorma.com.

**Comment by strogonoff** [comment]
@ronaldtse That’s quickstart for metanorma-iso isn’t it, for ISO specifically? If typical adopter is more of a corporate user, would something like https://github.com/riboseinc/metanorma-iso/blob/master/docs/customisation.adoc make more sense?

(The more I’m getting into the Metanorma the more I’m considering separate landing pages targeting different users: “for ISO standard authors”, “for corporate users”, etc. The existing documentation seems to try to address everything at once and is hence quite confusing.)

**Comment by ronaldtse** [comment]
@strogonoff Actually the quickstart for metanorma-iso is the most "general" syntax.

The typical adopter comes from different standard bodies (or corporates):

* ISO
* CalConnect
* IETF / RFC
* IEC
* Cloud Security Alliance
* etc.

We should definitely have different landing pages. Or even different sites?

**Comment by strogonoff** [comment]
These docs were made part of [Metanorma-ISO package docs](https://www.metanorma.com/software/metanorma-iso/) on the site now. Designs given don’t specify how screens for non-software documentation pages (“project-wide” docs) would look, but I have some ideas for how this should be implemented to simplify adoption.

**Comment by ronaldtse** [comment]
@strogonoff I am speechless -- the results are impressive!!!

Could we bother you to create a blog post announcing (and giving a link to the new docs)? Many would love to see this.

**Comment by ronaldtse** [comment]
Perhaps @opoudjis would like to say something too in the blog post.

**Comment by strogonoff** [comment]
@ronaldtse 

Thank you! Of course the content was written by @opoudjis, although I took the liberty of splitting it into sections and am working on better presentation of it in context of the site and output formatting.

A question, you wrote earlier:

> The typical adopter comes from different standard bodies (or corporates)

Do I understand correctly that an average arbitrary organization seeking to establish a workflow for its internal specs (let’s say Adobe or Mozilla) is a bit far-fetched at this point, and we focus on major bodies that you mentioned?

**Comment by ronaldtse** [comment]
> Do I understand correctly that an average arbitrary organization seeking to establish a workflow for its internal specs (let’s say Adobe or Mozilla) is a bit far-fetched at this point, and we focus on major bodies that you mentioned?

We are currently on-boarding a large organization for this, so hopefully it won't be far fetched for long 😉  We should indeed cater for both cases!

**Comment by strogonoff** [comment]
I went ahead and implemented some of the ideas I mentioned I had in https://github.com/riboseinc/metanorma.com/issues/19#issuecomment-425108923, first pass visible on https://www.metanorma.com/ as of last night and IMO qualifies this to be closed
