### ISSUE TITLE
Provide installation instructions as updated in https://github.com/riboseinc/metanorma

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma.com#22]
Installation instructions given in https://github.com/riboseinc/metanorma for macOS, Linux and Windows platforms.

**Comment by strogonoff** [comment]
Should be fixed as of https://github.com/riboseinc/metanorma.com/commit/afe42def00c5aa9bf1f2f7ed89e98c482a5ded4a

It would’ve been live sooner but PR for docs is still pending: https://github.com/riboseinc/metanorma-cli/pull/4

**Comment by strogonoff** [comment]
I just changed docs repo URL to my fork for now

**Comment by strogonoff** [comment]
I was wrong still open since docs concern more than CLI gem
