### ISSUE TITLE
CI not building the site?

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/metanorma.com#23]
I believe the update was pushed a while ago (yesterday), but it’s not reflected on www.metanorma.com still.

Is CI build failing with the newest theme/helpers gem version? Or is it something like CDN caching?

**Comment by ronaldtse** [comment]
@strogonoff it's being updated at the moment by @kwkwan . Stay tuned!

**Comment by strogonoff** [comment]
Awesome! Not having visibility into this I get worried after major theme releases (in case CI env differs from my local one things might break)

**Comment by strogonoff** [comment]
@kwkwan Indeed. Couple of regressions after a refactor were identified and fixed. Could you try with latest changes?

**Comment by ronaldtse** [comment]
It's already been built and deployed https://travis-ci.com/riboseinc/metanorma.com

BTW, it's still using the purple color and only "c" changes to blue. Is this intended?

**Comment by strogonoff** [comment]
@ronaldtse actually the colors are due to be updated in https://github.com/riboseinc/metanorma.com/issues/17, I missed the fact that it’s unblocked & I can deal with it now
