### ISSUE TITLE
Remove "is ribose open" from hero image on index

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma.com#24]
It appears that we don't want to be too hard-sell, and it's sufficient to keep "ribose open" in the footer.  We prefer people judging us after using the toolchain rather than to display the affiliation early on.

What do you think?

**Comment by strogonoff** [comment]
I’d take care of toning down the hub label in the upcoming design iteration of the Open Project theme. (If there is a reason you would like to expedite this fix for Ribose Open network, let me know)

**Comment by strogonoff** [comment]
Upstream issue https://github.com/riboseinc/jekyll-theme-open-project/issues/41

**Comment by ronaldtse** [comment]
It's not an urgent issue, but it would be great to start with the Metanorma site soon. 👍
