### ISSUE TITLE
Add UNECE documentation

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma.com#27]
Example documents below.

Recommendation:
https://github.com/riboseinc/unece-docs/blob/master/unece-rec42.adoc

Plenary document:
https://github.com/riboseinc/unece-docs/blob/master/unece-plenary.adoc

**Comment by opoudjis** [comment]
I have not yet added technical documentation to the gem, and there are idiosyncrasies (and will be more). Anton, wait until I have added technical documentation, and that will likely not be for a couple of weeks.

**Comment by opoudjis** [comment]
There is now technical documentation in place, in the UNECE readme, and in the tips in the quickstart and guidance docs. However, there's about to be a whole lot more stuff put into UNECE from the UN style guide. @ronaldtse, should @strogonoff wait on this, or start doing things with it? And does this remain High Priority for me?

**Comment by ronaldtse** [comment]
Yes it’s high time to get this rolling. Thanks :wink:

**Comment by opoudjis** [comment]
@strogonoff The raw material is the metanora-unece Readme, and the Tips I have added in to the Quickstart and Guidance documents. 

Could you start drawing  up a framework for documentation?

**Comment by strogonoff** [comment]
Live alongside other flavours under metanorma.com/author
