### ISSUE TITLE
Metanorma.com does not resolve without www. prefix

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/metanorma.com#3]

**Comment by ronaldtse** [comment]
We can enable the root apex for the metanorma.com domain indeed.

https://aws.amazon.com/blogs/aws/root-domain-website-hosting-for-amazon-s3/

**Comment by strogonoff** [comment]
@ronaldtse I see, this appears to belong on Terraform level so I filed https://github.com/riboseinc/terraform-aws-s3-cloudfront-website/issues/2. Not sure know how to implement so hopefully someone can take this.

**Comment by ronaldtse** [comment]
https://github.com/riboseinc/terraform-aws-s3-cloudfront-website/issues/2 is now done and metanorma.com root redirects properly now, closing.
