### ISSUE TITLE
Incorporate metanorma-model-* documentation to metanorma.com

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma.com#34]
For example, metanorma-model-iso provides the data models for the ISO document class. We should provide those on metanorma.com together with description on what they mean.

**Comment by ronaldtse** [comment]
Ping @strogonoff

**Comment by strogonoff** [comment]
Pushed an update enabling incorporated StanDoc & CSAND model display. The rest will follow as soon as it’s confirmed CI works and all (there’s a new dependency in the gem, it’s not as crazy as PlantUML but it requires a gem to get PNG file dimensions).
