### ISSUE TITLE
Add page on how to cite things, such as using the ISO(...) or ISO ... syntax

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma.com#36]
We do need an individual page on metanorma.com on how to cite things, such as using the `ISO(...)` or `ISO ...` syntax.

From https://github.com/riboseinc/metanorma-iso/issues/217

**Comment by opoudjis** [comment]
The relaton README already says this, but I'll expand on this as a blog article. 

After I have introduced bibliographies and relaton.

**Comment by opoudjis** [comment]
Adding this to the Part 4 blog article on writing Metanorma documents, which addresses those issues as well.
