### ISSUE TITLE
Find content for metanorma.com

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/metanorma.com#4]
Including migrating wiki content about gems into docs/ for those gems.

@strogonoff, this is going to take a while, and the docs are going to need refactoring; I'll keep you informed as I do this.

**Comment by opoudjis** [comment]
@strogonoff : We're an Asciidoc shop, at least at this stage of Metanorma; so Markdown documents are a surprise to see in https://github.com/riboseinc/asciidoctor-rfc/tree/master/docs :-)

I'm going to dump here all content you will need to draw on for Metanorma. I've written almost all of it. I'm pretty overloaded, so I'm expecting you to sort through it...

* asciidoctor-rfc
** https://github.com/riboseinc/asciidoctor-rfc/blob/master/README.adoc
** https://datatracker.ietf.org/doc/draft-ribose-asciirfc/ (to be published soon)
** https://github.com/riboseinc/rfc-asciirfc-minimal

* asciidoctor-iso
** https://github.com/riboseinc/asciidoctor-iso/blob/master/README.adoc
** https://github.com/riboseinc/asciidoctor-iso/blob/master/docs/customisation.adoc
** https://github.com/riboseinc/asciidoctor-iso/blob/master/docs/guidance.adoc
** https://github.com/riboseinc/asciidoctor-iso/blob/master/docs/quickstart.adoc

* metanorma-macos-setup
** https://github.com/riboseinc/metanorma-macos-setup/blob/master/README.adoc

**Comment by strogonoff** [comment]
@opoudjis yep—the priority was to get the websites up. As I mentioned, dogfooding the technology promoted is an important thing too and it’s on the roadmap! That said, if there’ll be hitches implementing AsciiDoc support in Jekyll site suite, we’ll stick to Markdown (a rewrite of source docs in different syntax can be done at any time).

Thanks for the links. We’ll need the content in a different format to accommodate website designs (things like project pitch, introductory blog post, etc.), but I expect the existing docs and working with project maintainers would provide the necessary building blocks for that.

For now let me know if you have any ideas for how to summarize the gist of Metanorma (as the umbrella project) in 15–20 words and 1–2 sentences (those limits are fluid). So far formulating the core idea remains a challenge for me :) (This is filed in https://github.com/riboseinc/metanorma.com/issues/2, I’m also considering a brief voice standup meeting with you and @ronaldtse to get a better hang of this)

**Comment by strogonoff** [comment]
I’m marking this as malformed (not specific enough) and closing in favor of #1, #2, #5, #6

**Comment by strogonoff** [comment]
@opoudjis I think I’m an hour apart with Ronald as of now… I call up with a colleague in NZ sometimes so this should be doable perhaps at something like UTC 0000, we’ll see what works for everyone.

I used “standup meeting” as a shortcut for a time-restricted chat where everyone is impatient to get back to business, partly to keep in check my own tendency to ramble 😉

(as for voice that’s an optional choice for practical reasons to reserve your and everyone’s bandwidth for clearer sound)
