### ISSUE TITLE
Quickstart document in mobile screen mode unable to see content at the right hand side

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma.com#48]
In this screenshot, the content at the right hand side cannot be scrolled-to or seen. I think some responsiveness is necessary.

![img_3683](https://user-images.githubusercontent.com/11865/49992783-ffc90280-ffbf-11e8-87cb-38902d24c649.png)

**Comment by strogonoff** [comment]
I believe this was fixed in one of the later releases last year (tested on Firefox & WebKit), if still reproducible please reopen & let me know which browser this happens under
