### ISSUE TITLE
New blog post for installing Metanorma using Chocolatey

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma.com#50]
Draft text below.

Metanorma now awailable for Windows as chocoltey package!

{Date}

for a long time in the world of windows there was no tool for installing software in the "Linux style", but the situation is beginning to change ...

In 2011, a tool called Chocolatey was released.

Chocolatey is a package manager and installer for software packages, built for the Windows NT platform. It is an execution engine using the NuGet packaging infrastructure and Windows PowerShell to provide an automation tool for installing software on Windows machines, designed to simplify the process from the user perspective.

To install Chocolatey you can followup this guide https://chocolatey.org/docs/installation

Once it's installed you can get metanorma in one single command `cinst metanorma`

By the end of this command you will get 

```
Environment Vars (like PATH) have changed. Close/reopen your shell to see the changes (or in powershell/cmd.exe just type `refreshenv`). 
 The install of metanorma was successful.
   Software install location not explicitly set, could be in package or
   default install location if installer.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

Done! Now you are ready to use metanorma CLI tool

Learn more about about how Metanorma can help you create and unify your standards at https://www.metanorma.com.

Linked articles:

[Why Chocolatey?](https://chocolatey.org/docs/why)

**Comment by opoudjis** [comment]
Done.
