### ISSUE TITLE
Blog author details

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/metanorma.com#53]
@opoudjis can I have your details to add a pretty author block with your face as assumed by theme design? Need an email (best if it’s associated with a Gravatar pic, currently the only out-of-the-box way to show author’s photo), any profile links (Twitter, LinkedIn, FB, etc) are good too

There’s a YAML frontmatter structure that makes this work, I can add it to the existing posts.

**Comment by opoudjis** [comment]
Sure, but don't have much time this week. Next week ok?

**Comment by strogonoff** [comment]
Sounds good, thanks :)

**Comment by opoudjis** [comment]
My LinkedIn: https://www.linkedin.com/in/opoudjis/
Gravatar: https://en.gravatar.com/opoudjis
Associated email: opoudjis@optusnet.com.au
And of course GitHub profile: https://github.com/opoudjis

**Comment by strogonoff** [comment]
Thanks! Will add @opoudjis info to blog posts as appropriate For @ronaldtse I’ll add a small feature to the theme allowing author photos to be placed in site assets (currently author photos only work through Gravatar integration).

**Comment by ronaldtse** [comment]
Awesome!

**Comment by strogonoff** [comment]
@ronaldtse @opoudjis Please let me know if I misattributed any posts: https://www.metanorma.com/blog/
