### ISSUE TITLE
New topic: Recommend text editors 

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma.com#59]
Users of metanorma wish to know what editors are recommended for its usage.

The recommended ones from users are:
- Atom with Asciidoctor plugin
- Microsoft VScode with AsciiDoc preview

**Comment by strogonoff** [comment]
Fixed in https://github.com/riboseinc/metanorma.com/commit/96abd24c355073853e03c6aa4d14cb19262d7f8a (wrong commit message)
