### ISSUE TITLE
Add OGC flavor to site

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma.com#62]
Metanorma-OGC is now an officially supported flavor for OGC documents.

The related repos are:
* https://github.com/riboseinc/metanorma-model-ogc/
* https://github.com/riboseinc/metanorma-ogc/

This task is to add the sections for OGC in Metanorma.com.

I will follow up with adding an OGC quick start guide like the one for CalConnect.

**Comment by strogonoff** [comment]
@ronaldtse I’m not sure which quick start you have in mind? Seems like docs are all fine.

**Comment by ronaldtse** [comment]
The quick start for CalConnect, OGC should be customized for their authors. I will post separate tasks about them.

**Comment by strogonoff** [comment]
We have that at https://metanorma.com/author/csd/ but sure please file issues if needs improvement!

**Comment by strogonoff** [comment]
I closed this since OGC flavour was added. If quick-start needs improvement I’m up for working on it,  but probably worth filing separately since I assume it applies to other flavours not just OGC (cc @ronaldtse)
