### ISSUE TITLE
Flavors: mark which ones are "alpha" which ones are "production"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma.com#63]
Production

* ISO
* IETF
* UN/ECE
* CSA
* CalConnect
* OGC
* Ribose

Alpha

* 国标
* M3AAWG
* ITU
* MPFA

**Comment by strogonoff** [comment]
What characterizes an “alpha” flavour?

**Comment by ronaldtse** [comment]
It’s more of a generic label for now, but generally it means that documents generated with those flavors have not been tested with the publication process of that SDO.

**Comment by ronaldtse** [comment]
Maybe we can consider that “Beta”...?

**Comment by strogonoff** [comment]
I like “beta” more!

**Comment by ronaldtse** [comment]
There we go 👍

**Comment by strogonoff** [comment]
Considering as done as of https://github.com/riboseinc/metanorma.com/commit/bc78caa02681bd659799ac2edae96f3e5028f386
