### ISSUE TITLE
Add ITU flavor to site

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma.com#64]
This is an alpha release but Metanorma-ITU is already quite useable.

Related repos:

* Models: https://github.com/riboseinc/metanorma-model-itu
* Processor: https://github.com/riboseinc/metanorma-itu
* Sample docs: https://github.com/riboseinc/mn-itu-docs

**Comment by strogonoff** [comment]
Considering it done: https://www.metanorma.com/author/itu/

As an aside, will update flavour templates to link model diagrams to flavours (similar to implementing gems) consistently.
