### ISSUE TITLE
Update Metanorma logo and design

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma.com#8]
According to Ricardo's latest site design.

The Metanorma logo is now uploaded here: https://github.com/riboseinc/open-design

**Comment by strogonoff** [comment]
I believe the symbol and the logo is the only design change at the time. Updated with 4c8e3b10ff04e732aada672f51d22a0ecac5c3cb, f5886a4bd5fbfed96229022bee0db8365095497f, 816e1774b12ac40ae2b40d86d954ea57718ec834, will close when changes are confirmed on live site.

**Comment by ronaldtse** [comment]
Yup it's updated. Thanks @strogonoff !
